### ISSUE TITLE
kubernetes is always starting but could not started

### ISSUE THREAD

**Issue by davidsmithgf** [Seanwong933/.NET-Core-on-Kubernetes#1]
按https://siegrain.wang/article/2018/11/26/getting-start-with-net-core-on-kubernetes学习中。
现在执行完 .\load_images.ps1，未报错，退回命令提示符状态。

但下一步 docker中 开启 Kubernetes，一直是黄灯，显示kubernetes is starting，一天一夜仍然无动静。

请问哪里看日志？或者哪里有进度可以查询？

**Comment by siegrainwong** [comment]
1. 检查你的docker版本是否跟 https://github.com/AliyunContainerService/k8s-for-docker-desktop 项目中描述的一致。
2. 这个也可能是因为国内镜像不稳定，可以添加其他镜像
```
http://f1361db2.m.daocloud.io
https://3laho3y3.mirror.aliyuncs.com
http://hub-mirror.c.163.com/
```
这些都可以加上去。

3. 这个正常来说绝不会超过1小时，如果超过了就直接重启docker，甚至重启计算机再试，没有进度可以查询，这是kubernetes安装的硬伤。

按这个顺序排查即可。
